image:
  repository: octoprint/octoprint
  tag: 1.8.7
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

env:
  MJPEG_STREAMER_AUTOSTART: "{{ .Values.persistence.webcam.enabled }}"
  OCTOPRINT_PORT: 80

persistence:
  config:
    enabled: true
    type: pvc
    size: 1Gi
  printer:
    enabled: true
    type: hostPath
    # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
    # Instead, use the /dev/serial/by-id/X serial device for your printer.
    hostPath: /dev/serial/by-id/usb-Prusa_Research__prusa3d.com__Original_Prusa_i3_MK3_CZPX0221X004XK44811-if00
    hostPathType: CharDevice
    mountPath: /dev/printer
  webcam:
    enabled: true
    type: hostPath
    hostPath: /dev/video0
    hostPathType: CharDevice

service:
  main:
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: nigelarmstrong-me-issuer
    hosts:
    - host: octoprint.kube.home.nigelarmstrong.me
      paths:
      - path: /
        pathType: Prefix
    tls:
    - secretName: octopritn-kube-home-nigelarmstrong-me-tls
      hosts:
      - octoprint.kube.home.nigelarmstrong.me


affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: feature.node.kubernetes.io/usb-02_2c99_0002.present
          operator: In
          values:
          - "true"

podAnnotations:
  descheduler.alpha.kubernetes.io/evict: "true"
