replicaCount: 1

image:
  repository: octoprint/octoprint
  tag: 1.8.7
  pullPolicy: IfNotPresent


# Only one of hostPrinter or tcpPrinter should be enabled.
hostPrinter:
  enabled: true
  # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
  # Instead, use the /dev/serial/by-id/X serial device for your printer.
  hostPath: /dev/serial/by-id/usb-Prusa_Research__prusa3d.com__Original_Prusa_i3_MK3_CZPX0221X004XK44811-if00
  hostPathType: File

tcpPrinter:
  enabled: false
  host: "printer.example.com"
  port: 3333

webcam:
  enabled: true
  hostPath: /dev/video0
  hostPathType: File

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: nigelarmstrong-me-issuer
  paths: ["/"]
  hosts: ["octoprint.kube.home.nigelarmstrong.me"]
  tls:
  - secretName: octopritn-kube-home-nigelarmstrong-me-tls
    hosts:
    - octoprint.kube.home.nigelarmstrong.me

resources: {}
nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: feature.node.kubernetes.io/usb-02_2c99_0002.present
          operator: In
          values:
          - "true"

podAnnotations:
  descheduler.alpha.kubernetes.io/evict: "true"
